import os
from datetime import datetime

def generate_device_report(device: dict, nmap_result: dict,
                            cves_by_service: dict) -> str:
    """
    Generates a plain text vulnerability report for one device.
    Returns the report as a string.
    """
    now  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ip   = device.get("ip",       "unknown")
    host = device.get("hostname", "unknown")
    vend = device.get("vendor",   "unknown")
    mac  = device.get("mac",      "unknown")
    port = device.get("port",     "")
    note = device.get("notes",    "")

    lines = []
    lines.append("═" * 60)
    lines.append("  NETPYWIZ VULNERABILITY REPORT")
    lines.append("═" * 60)
    lines.append(f"  Device IP   : {ip}")
    lines.append(f"  Hostname    : {host}")
    lines.append(f"  Vendor      : {vend}")
    lines.append(f"  MAC Address : {mac}")
    lines.append(f"  Switch Port : {port or 'Not set'}")
    lines.append(f"  Scan Date   : {now}")
    lines.append("═" * 60)
    lines.append("")

    # Firewall
    os_guess = nmap_result.get("os_guess", "Unknown")
    fw_keywords = ["firewall", "fortinet", "paloalto", "pfsense",
                   "checkpoint", "sonicwall", "cisco asa", "juniper"]
    firewall_detected = any(kw in os_guess.lower() for kw in fw_keywords)

    lines.append("FIREWALL DETECTION")
    lines.append("─" * 40)
    if firewall_detected:
        lines.append(f"  ⚠ FIREWALL DETECTED: {os_guess}")
    else:
        lines.append(f"  OS/Device : {os_guess}")
    lines.append("")

    # Open ports
    ports = nmap_result.get("ports", [])
    lines.append("OPEN PORTS & SERVICES")
    lines.append("─" * 40)
    if not ports:
        lines.append("  No open ports found")
    else:
        for p in ports:
            lines.append(
                f"  Port {p['port']}/{p['protocol']:<4}  {p['service']}")
    lines.append("")

    # CVEs
    all_cves = []
    for svc, cves in cves_by_service.items():
        for c in cves:
            if "error" not in c:
                all_cves.append(c)

    lines.append("VULNERABILITIES")
    lines.append("─" * 40)

    if not all_cves:
        lines.append("  No known vulnerabilities found for detected services")
    else:
        # Group by severity
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"]:
            sev_cves = [c for c in all_cves if c["severity"] == sev]
            if not sev_cves:
                continue
            for c in sev_cves:
                lines.append(f"  [{c['severity']}]  {c['id']}"
                             + (f"  (Score: {c['score']})" if c['score'] else ""))
                lines.append(f"  Service : {c['service']}")
                lines.append(f"  Summary : {c['summary']}")
                lines.append(f"  Details : {c['url']}")
                lines.append("")

    # Notes
    if note:
        lines.append("NOTES")
        lines.append("─" * 40)
        lines.append(f"  {note}")
        lines.append("")

    lines.append("═" * 60)
    lines.append("  Generated by NetPyWiz — Network Monitor & Security Tool")
    lines.append("═" * 60)

    return "\n".join(lines)


def save_device_report(report_str: str, ip: str, folder: str) -> str:
    """Saves report to folder/IP_vulnerability.txt"""
    import pwd
    filename = f"{ip.replace('.', '_')}_vulnerability.txt"
    filepath = os.path.join(folder, filename)
    with open(filepath, "w") as f:
        f.write(report_str)
    # Fix ownership so real user can delete it
    try:
        real_user = (os.environ.get("SUDO_USER") or os.environ.get("USER"))
        pw        = pwd.getpwnam(real_user)
        os.chown(filepath, pw.pw_uid, pw.pw_gid)
    except Exception:
        pass
    return filepath
